services:
  acg-benefit-test:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: 'benefit_test'
    deploy:
      # 자원 정책
      resources:
        limits:
          memory: '1G'
        reservations:
          cpus: '1'
    networks:
      - acg-benefit-net_default
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./src:/myfolder/src
      - ./logs:/myfolder/logs
      - ./resource:/myfolder/resource
    env_file:
      - './.env'
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mongo-benefit

  redis-benefit:
    image: redis:latest
    container_name: redis-benefit
    restart: on-failure
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - acg-benefit-net_default

  mariadb-benefit:
    image: mariadb:latest
    container_name: mariadb-benefit
    restart: on-failure
    volumes:
      - ./db/conf.d:/etc/mysql/conf.d
      - ./db/data:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    env_file: .env
    environment:
      TZ: Asia/Seoul
      MARIADB_ROOT_PASSWORD: $DB_PW
      MARIADB_DATABASE: $DB_NAME
    ports:
      - '3307:3306'
    deploy:
      resources:
        limits:
          memory: '512M'
        reservations:
          cpus: '0.5'
    networks:
      - acg-benefit-net_default

networks:
  acg-benefit-net_default:
    driver: bridge
