services:
  acg-benefit-test:
    build:
      context: '.'
      dockerfile: Dockerfile
    container_name: 'benefit_test'
    deploy:
      # 자원 정책
      resources:
        limits:
          memory: '1G'
        reservations:
          cpus: '1'
    networks:
      - acg-benefit-net_default
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - ./src:/myfolder/src
      - ./logs:/myfolder/logs
      - ./resource:/myfolder/resource
    env_file:
      - './.env'
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - mongo-benefit

  redis-benefit:
    image: redis:latest
    container_name: redis-benefit
    restart: on-failure
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - acg-benefit-net_default

  mongo-benefit:
    image: mongo:latest
    container_name: mongo-benefit
    restart: on-failure
    volumes:
      - ./mongo-data:/data/db
    ports:
      - '27017:27017'
    networks:
      - acg-benefit-net_default

networks:
  acg-benefit-net_default:
    driver: bridge
