import { ConfirmEnum } from '../../../../common/constant/enum';
import { SwaggerMethod } from '../../../../common/interface/swagger.interface';
import { UpdateConfirmDto } from '../dto/updateConfirm.dto';

export const USERS_INTRANET_APPROVAL: SwaggerMethod = {
  GET: {
    API_OPERATION: {
      summary: '결재 승인 내역 조회하기 API',
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 200,
            message: 'success',
            data: [
              {
                commuteIdx: 180,
                commuteDate: '2025-03-28',
                userIdx: 1,
                userName: '김현민',
                leaveTypeIdx: 20,
                leaveType: '병가',
                note: null,
                confirmYN: 'N',
                confirmDate: null,
                rejectDate: null,
                confirmPersonIdx: null,
                createdAt: '2025-03-27T00:57:34.468Z',
                relationType: 'CC',
                confirmStatus: '승인 대기',
              },
              {
                commuteIdx: 143,
                commuteDate: '2025-03-15',
                userIdx: 2,
                userName: '이승현',
                leaveTypeIdx: 3,
                leaveType: '오후 반차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:44:52.332Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 144,
                commuteDate: '2025-03-14',
                userIdx: 2,
                userName: '이승현',
                leaveTypeIdx: 6,
                leaveType: '연차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:45:11.138Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 145,
                commuteDate: '2025-03-18',
                userIdx: 2,
                userName: '이승현',
                leaveTypeIdx: 4,
                leaveType: '오전 반반차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:45:11.139Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 147,
                commuteDate: '2025-03-18',
                userIdx: 1,
                userName: '김현민',
                leaveTypeIdx: 3,
                leaveType: '오후 반차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:45:41.166Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 149,
                commuteDate: '2025-03-19',
                userIdx: 1,
                userName: '김현민',
                leaveTypeIdx: 3,
                leaveType: '오후 반차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:45:49.120Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 153,
                commuteDate: '2025-03-09',
                userIdx: 9,
                userName: '김정현',
                leaveTypeIdx: 7,
                leaveType: '특별 휴무',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:47:36.287Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 154,
                commuteDate: '2025-03-15',
                userIdx: 5,
                userName: '김현근',
                leaveTypeIdx: 7,
                leaveType: '특별 휴무',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:59:54.729Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 155,
                commuteDate: '2025-03-14',
                userIdx: 5,
                userName: '김현근',
                leaveTypeIdx: 7,
                leaveType: '특별 휴무',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T05:59:54.731Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 156,
                commuteDate: '2025-03-14',
                userIdx: 1,
                userName: '김현민',
                leaveTypeIdx: 7,
                leaveType: '특별 휴무',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-14',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-14T06:01:22.394Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-14',
              },
              {
                commuteIdx: 183,
                commuteDate: '2025-03-29',
                userIdx: 1,
                userName: '김현민',
                leaveTypeIdx: 6,
                leaveType: '연차',
                note: null,
                confirmYN: 'Y',
                confirmDate: '2025-03-27',
                rejectDate: null,
                confirmPersonIdx: 5,
                createdAt: '2025-03-27T01:53:12.243Z',
                relationType: 'APPROVER',
                confirmStatus: '2025-03-27',
              },
            ],
          },
        },
      },
    },
  },
  PATCH: {
    API_OPERATION: {
      summary: '휴가 승인/반려하기 API',
    },
    API_PARAM1: {
      type: Number,
      name: 'commuteIdx',
      required: true,
      description: 'IDX',
    },
    API_BODY: {
      type: UpdateConfirmDto,
      examples: {
        a: {
          summary: '승인',
          value: {
            confirmYN: ConfirmEnum.YES,
          },
        },
        b: {
          summary: '반려',
          value: {
            confirmYN: ConfirmEnum.REJECT,
          },
        },
      },
      required: true,
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 200,
            message: 'success',
          },
        },
      },
    },
  },
};
