import { SwaggerMethod } from '../../../../common/interface/swagger.interface';
import { CheckInDto } from '../dto/checkIn.dto';
import { CheckOutDto } from '../dto/checkOut.dto';
import { UpdateCommuteTimeDto } from '../dto/updateCommuteTime.dto';

export const USERS_INTRANET_CHECK_IN: SwaggerMethod = {
  POST: {
    API_OPERATION: {
      summary: '출근 찍기 API',
    },
    API_BODY: {
      type: CheckInDto,
      examples: {
        a: {
          summary: '예시',
          value: {
            checkInDeviceType: 'PC',
            checkInTime: '2025-01-13T00:16:15.759Z',
          },
        },
      },
      required: true,
    },
    API_CREATED_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 201,
            message: 'success',
            data: {
              checkInTime: '2025-01-13T00:16:15.759Z',
            },
          },
        },
      },
    },
    API_BAD_REQUEST_RESPONSE: {
      content: {
        'application/json': {
          examples: {
            a: {
              summary: '이미 출근 찍었다면',
              value: {
                message: '이미 출근이 등록되었습니다.',
                error: 'Bad Request',
                statusCode: 400,
                timeStamp: '2025. 1. 13. 오후 4:47:50',
                path: '/users/intranet/check-in',
              },
            },
            b: {
              summary: '연차/휴무일에 출근 찍었다면',
              value: {
                message: '오늘은 연차/휴무 날 입니다.',
                error: 'Bad Request',
                statusCode: 400,
                timeStamp: '2025. 1. 17. 오전 10:27:28',
                path: '/users/intranet/check-in',
              },
            },
          },
        },
      },
    },
  },
};

export const USERS_INTRANET_CHECK_OUT: SwaggerMethod = {
  PUT: {
    API_OPERATION: {
      summary: '퇴근 찍기 API',
    },
    API_BODY: {
      type: CheckOutDto,
      examples: {
        a: {
          summary: '정상 퇴근',
          value: {
            checkOutDeviceType: 'PC',
            checkOutTime: '2025-01-13T09:16:15.759Z',
            earlyLeaveReason: null,
          },
        },
        b: {
          summary: '조기 퇴근',
          value: {
            checkOutDeviceType: 'PC',
            checkOutTime: '2025-01-13T04:16:15.759Z',
            earlyLeaveReason: '워크샵 조기퇴근',
          },
        },
      },
      required: true,
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 200,
            message: 'success',
            data: {
              checkOutTime: '2025-01-13T09:16:15.759Z',
            },
          },
        },
      },
    },
    API_BAD_REQUEST_RESPONSE: {
      content: {
        'application/json': {
          examples: {
            a: {
              summary: '출근 정보가 없다면',
              value: {
                message: '출근을 먼저 등록해주세요',
                error: 'Bad Request',
                statusCode: 400,
                timeStamp: '2025. 1. 13. 오후 4:47:50',
                path: '/users/intranet/check-out',
              },
            },
            b: {
              summary: '조기퇴근 시, 사유 입력 필수',
              value: {
                message: '근무시간이 9시간 미만일 경우, 조기 퇴근 사유이 필수입니다.',
                error: 'Bad Request',
                statusCode: 400,
                timeStamp: '2025. 1. 14. 오전 10:49:08',
                path: '/users/intranet/check-out',
              },
            },
            c: {
              summary: '이미 퇴근을 찍었다면',
              value: {
                message: '이미 퇴근을 찍었습니다.',
                error: 'Bad Request',
                statusCode: 400,
                timeStamp: '2025. 1. 17. 오전 10:07:04',
                path: '/users/intranet/check-out',
              },
            },
          },
        },
      },
    },
  },
};

export const ADMIN_INTRANET_COMMUTE: SwaggerMethod = {
  DELETE: {
    API_OPERATION: {
      summary: '어드민 출퇴근 내역 삭제 API',
    },
    API_BODY: {
      type: Array,
      description: '근태내역IDX 배열',
      examples: {
        a: {
          summary: '개별삭제',
          value: { commuteIdxList: [1] },
        },
        b: {
          summary: '복수삭제',
          value: { commuteIdxList: [1, 2, 3] },
        },
      },
      required: true,
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {},
        },
      },
    },
  },
  GET: {
    API_OPERATION: {
      summary: '어드민 출퇴근 관리 조회 API',
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 200,
            message: 'success',
            data: {
              totalPage: 1,
              total: 11,
              records: [
                {
                  commuteIdx: 30,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: '2025-01-29T00:16:16.000Z',
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: '정상',
                  attendance: '정상 출근',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: '172.19.0.1',
                  checkOutIpAddr: null,
                  checkInDeviceType: 'PC',
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:27:07.946Z',
                  updatedAt: '2025-01-17T01:27:07.946Z',
                },
                {
                  commuteIdx: 29,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '연차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:26:46.000Z',
                  updatedAt: '2025-01-17T01:26:46.000Z',
                },
                {
                  commuteIdx: 28,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '보건 휴가',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:26:31.000Z',
                  updatedAt: '2025-01-17T01:26:31.000Z',
                },
                {
                  commuteIdx: 27,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '오후 반차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:26:10.000Z',
                  updatedAt: '2025-01-17T01:26:10.000Z',
                },
                {
                  commuteIdx: 26,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '오후 반반차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:26:00.000Z',
                  updatedAt: '2025-01-17T01:26:00.000Z',
                },
                {
                  commuteIdx: 25,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '오전 반반차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:25:44.000Z',
                  updatedAt: '2025-01-17T01:25:44.000Z',
                },
                {
                  commuteIdx: 24,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: null,
                  checkOutTime: null,
                  workingMinutes: null,
                  overtimeWorkingMinutes: null,
                  lateStatus: null,
                  attendance: '오전 반반차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: null,
                  checkOutIpAddr: null,
                  checkInDeviceType: null,
                  checkOutDeviåceType: null,
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:25:38.000Z',
                  updatedAt: '2025-01-17T01:25:38.000Z',
                },
                {
                  commuteIdx: 23,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: '2025-01-02T05:16:16.000Z',
                  checkOutTime: '2025-01-02T09:17:21.000Z',
                  workingMinutes: 241,
                  overtimeWorkingMinutes: 1,
                  lateStatus: '정상',
                  attendance: '오전 반차',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: '172.19.0.1',
                  checkOutIpAddr: '172.19.0.1',
                  checkInDeviceType: 'PC',
                  checkOutDeviåceType: 'PC',
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:25:15.000Z',
                  updatedAt: '2025-01-17T02:06:15.000Z',
                },
                {
                  commuteIdx: 22,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: '2025-01-16T00:16:16.000Z',
                  checkOutTime: '2025-01-16T11:16:21.000Z',
                  workingMinutes: 660,
                  overtimeWorkingMinutes: 120,
                  lateStatus: '정상',
                  attendance: '정상 출근',
                  updateReason: null,
                  earlyLeaveReason: '그냥',
                  note: null,
                  checkInIpAddr: '172.19.0.1',
                  checkOutIpAddr: '172.19.0.1',
                  checkInDeviceType: 'PC',
                  checkOutDeviåceType: 'PC',
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:11:07.363Z',
                  updatedAt: '2025-01-17T01:17:26.000Z',
                },
                {
                  commuteIdx: 21,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: '2025-01-18T02:16:16.000Z',
                  checkOutTime: '2025-01-18T09:16:21.000Z',
                  workingMinutes: 420,
                  overtimeWorkingMinutes: 0,
                  lateStatus: '지각',
                  attendance: '정상 출근',
                  updateReason: null,
                  earlyLeaveReason: '그냥',
                  note: null,
                  checkInIpAddr: '172.19.0.1',
                  checkOutIpAddr: '172.19.0.1',
                  checkInDeviceType: 'PC',
                  checkOutDeviåceType: 'PC',
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:02:50.789Z',
                  updatedAt: '2025-01-17T01:09:54.000Z',
                },
                {
                  commuteIdx: 20,
                  userIdx: 1,
                  id: 'shlee1',
                  userName: '이승현',
                  hqName: 'HR솔루션본부',
                  teamName: 'HR Tech',
                  gradeName: '대표',
                  checkInTime: '2025-01-17T00:16:16.000Z',
                  checkOutTime: '2025-01-17T09:16:21.000Z',
                  workingMinutes: 540,
                  overtimeWorkingMinutes: 0,
                  lateStatus: '정상',
                  attendance: '정상 출근',
                  updateReason: null,
                  earlyLeaveReason: null,
                  note: null,
                  checkInIpAddr: '172.19.0.1',
                  checkOutIpAddr: '172.19.0.1',
                  checkInDeviceType: 'PC',
                  checkOutDeviåceType: 'PC',
                  confirmYN: 'N',
                  confirmDate: null,
                  createdAt: '2025-01-17T01:01:49.401Z',
                  updatedAt: '2025-01-17T01:06:42.000Z',
                },
              ],
            },
          },
        },
      },
    },
  },
};

export const ADMIN_INTRANET_COMMUTE_TIME: SwaggerMethod = {
  PATCH: {
    API_OPERATION: {
      summary: '어드민 출퇴근 시간 수정 API',
    },
    API_PARAM1: {
      name: 'commuteIdx',
      type: Number,
      required: true,
      description: '근태내역IDX',
    },
    API_BODY: {
      type: UpdateCommuteTimeDto,
      required: true,
      examples: {
        a: {
          summary: '예시',
          value: {
            checkInTime: '2025-01-22T00:16:15.759Z',
            checkOutTime: '2025-01-22T10:16:15.759Z',
            updateReason: '사유사유',
          },
        },
      },
    },
    API_OK_RESPONSE: {
      content: {
        'application/json': {
          example: {
            statusCode: 200,
            message: 'success',
          },
        },
      },
    },
  },
};
