name: E2E Test & Merge to Dev
on:
  pull_request:
    branches: ['dev']
jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22.4.1

      - name: Install Dependencies
        run: npm install

      - name: create .env.test
        run: |
          touch .env.test
          echo "TEST_DB_NAME=${{ secrets.TEST_DB_NAME }}" >> .env.test
            echo "TEST_DB_HOST=${{ secrets.TEST_DB_HOST }}" >> .env.test
            echo "TEST_DB_PW=${{ secrets.TEST_DB_PW }}" >> .env.test
            echo "TEST_DB_PORT=${{ secrets.TEST_DB_PORT }}" >> .env.test
            echo "TEST_DB_USER=${{ secrets.TEST_DB_USER }}" >> .env.test
            echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env.test
            echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env.test
            echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> .env.test
            echo "AXIOS_TIMEOUT=${{ secrets.AXIOS_TIMEOUT }}" >> .env.test
            echo "AXIOS_MAX_REDIRECTS=${{ secrets.AXIOS_MAX_REDIRECTS }}" >> .env.test
            echo "HOLIDAY_API_URL=${{ secrets.HOLIDAY_API_URL }}" >> .env.test            
            echo "HOLIDAY_API_KEY=${{ secrets.HOLIDAY_API_KEY }}" >> .env.test            
            echo "AUTH_KEY_AES=${{ secrets.AUTH_KEY_AES }}" >> .env.test            
            echo "REDIS_HOST=${{ secrets.REDIS_HOST }}" >> .env.test            
            echo "REDIS_PORT=${{ secrets.REDIS_PORT }}" >> .env.test            
            echo "SERVER_URL=${{ secrets.SERVER_URL }}" >> .env.test
            echo "S3_ACCESS_KEY_ID=${{ secrets.S3_ACCESS_KEY_ID }}" >> .env.test
            echo "S3_SECRET_ACCESS_KEY=${{ secrets.S3_SECRET_ACCESS_KEY }}" >> .env.test
            echo "S3_REGION=${{ secrets.S3_REGION }}" >> .env.test            
            echo "S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}" >> .env.test
            echo "MONGODB_URL=${{ secrets.MONGODB_URL }}" >> .env.test

      - name: Run E2E Tests
        run: npm run test -- --maxWorkers=1

      - name: Close PR if Tests Fail
        if: failure()
        run: |
          PR_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")

          echo "❌ E2E 테스트 실패! PR #$PR_NUMBER을 닫습니다."

          curl -X PATCH -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/pulls/$PR_NUMBER \
              -d '{"state":"closed"}'
